DROP TABLE IF EXISTS quests;

CREATE TABLE quests(
    id INT AUTO_INCREMENT PRIMARY KEY,
    text VARCHAR(5000) NOT NULL,
    answer1 VARCHAR(2500) NOT NULL,
    answer2 VARCHAR(2500) NOT NULL,
    answer3 VARCHAR(2500) NOT NULL,
    answer4 VARCHAR(2500) NOT NULL,
    correct_answer VARCHAR(2500) NOT NULL
);